// Catalogo CandyShop — dati estratti da candyshopinternational.com (maggio 2026)
// Usato da prisma/seed.ts. Le immagini sono placeholder PNG generati on-the-fly
// (placehold.co) — sostituirle dal pannello admin con upload Cloudinary.

export type SeedCategory = {
  slug: string;
  nameIt: string;
  nameEn: string;
  sortOrder: number;
  color: string; // hex senza # per placehold.co
};

export type SeedBrand = {
  slug: string;
  name: string;
};

export type SeedProduct = {
  slug: string;
  nameIt: string;
  nameEn: string;
  descIt?: string;
  descEn?: string;
  priceCents: number;
  compareAtCents?: number;
  categorySlug: string;
  brandSlug: string;
  isNew?: boolean;
  isFeatured?: boolean;
  attributes?: Record<string, string>;
  imageColor?: string; // override colore placeholder
};

export const CATEGORIES: SeedCategory[] = [
  { slug: "cioccolato", nameIt: "Cioccolato", nameEn: "Chocolate", sortOrder: 1, color: "7B3F00" },
  { slug: "caramelle", nameIt: "Caramelle", nameEn: "Candy", sortOrder: 2, color: "FF1493" },
  { slug: "patatine-popcorn", nameIt: "Patatine & Popcorn", nameEn: "Chips & Popcorn", sortOrder: 3, color: "FFA500" },
  { slug: "bevande-americane", nameIt: "Bevande Americane", nameEn: "American Drinks", sortOrder: 4, color: "DC143C" },
  { slug: "snack-dolci", nameIt: "Snack Dolci", nameEn: "Sweet Snacks", sortOrder: 5, color: "FF69B4" },
  { slug: "cereali", nameIt: "Cereali", nameEn: "Cereals", sortOrder: 6, color: "FFD700" },
];

export const BRANDS: SeedBrand[] = [
  { slug: "reeses", name: "Reese's" },
  { slug: "snickers", name: "Snickers" },
  { slug: "twix", name: "Twix" },
  { slug: "kinder", name: "Kinder" },
  { slug: "hersheys", name: "Hershey's" },
  { slug: "oreo", name: "Oreo" },
  { slug: "pringles", name: "Pringles" },
  { slug: "chazz", name: "Chazz" },
  { slug: "jimmys", name: "Jimmy's" },
  { slug: "totas", name: "Totas" },
  { slug: "lays", name: "Lay's" },
  { slug: "coca-cola", name: "Coca-Cola" },
  { slug: "dr-pepper", name: "Dr Pepper" },
  { slug: "fanta", name: "Fanta" },
  { slug: "mountain-dew", name: "Mountain Dew" },
  { slug: "arizona", name: "Arizona" },
  { slug: "calypso", name: "Calypso" },
  { slug: "prime", name: "Prime" },
  { slug: "monster", name: "Monster" },
  { slug: "haribo", name: "Haribo" },
  { slug: "trolli", name: "Trolli" },
  { slug: "warheads", name: "Warheads" },
  { slug: "sour-patch", name: "Sour Patch Kids" },
  { slug: "nerds", name: "Nerds" },
  { slug: "skittles", name: "Skittles" },
  { slug: "mike-ike", name: "Mike and Ike" },
  { slug: "lucky-charms", name: "Lucky Charms" },
  { slug: "froot-loops", name: "Froot Loops" },
];

export const PRODUCTS: SeedProduct[] = [
  // ───────── CIOCCOLATO ─────────
  {
    slug: "twix-milk-drink-350ml",
    nameIt: "Twix Milk Drink 350ml",
    nameEn: "Twix Milk Drink 350ml",
    descIt: "Bevanda al latte con il gusto inconfondibile di Twix: caramello e biscotto.",
    descEn: "Milk drink with the unmistakable Twix flavor: caramel and biscuit.",
    priceCents: 250,
    categorySlug: "cioccolato",
    brandSlug: "twix",
    attributes: { peso: "350ml", origine: "USA" },
    isFeatured: true,
  },
  {
    slug: "twix-caramel-centres-144g",
    nameIt: "Twix Caramel Centres 144g",
    nameEn: "Twix Caramel Centres 144g",
    priceCents: 350,
    categorySlug: "cioccolato",
    brandSlug: "twix",
    attributes: { peso: "144g" },
  },
  {
    slug: "snickers-milk-drink-350ml",
    nameIt: "Snickers Milk Drink 350ml",
    nameEn: "Snickers Milk Drink 350ml",
    descIt: "Bevanda al latte ispirata alla famosa barretta Snickers con arachidi e caramello.",
    descEn: "Milk drink inspired by the famous Snickers bar with peanuts and caramel.",
    priceCents: 250,
    categorySlug: "cioccolato",
    brandSlug: "snickers",
    attributes: { peso: "350ml" },
    isNew: true,
  },
  {
    slug: "snickers-butterscotch-40g",
    nameIt: "Snickers Butterscotch 40g",
    nameEn: "Snickers Butterscotch 40g",
    priceCents: 250,
    categorySlug: "cioccolato",
    brandSlug: "snickers",
    attributes: { peso: "40g", gusto: "Butterscotch" },
    isNew: true,
  },
  {
    slug: "snickers-berry-whip-40g",
    nameIt: "Snickers Berry Whip 40g",
    nameEn: "Snickers Berry Whip 40g",
    priceCents: 250,
    categorySlug: "cioccolato",
    brandSlug: "snickers",
    attributes: { peso: "40g", gusto: "Berry Whip" },
    isNew: true,
  },
  {
    slug: "reeses-white-4-full-size",
    nameIt: "Reese's White 4 Full Size",
    nameEn: "Reese's White 4 Full Size",
    descIt: "Le iconiche Reese's Cups con cioccolato bianco e burro d'arachidi.",
    descEn: "The iconic Reese's Cups with white chocolate and peanut butter.",
    priceCents: 250,
    categorySlug: "cioccolato",
    brandSlug: "reeses",
    isFeatured: true,
    attributes: { gusto: "Cioccolato bianco" },
  },
  {
    slug: "reeses-nutrageous-47g",
    nameIt: "Reese's Nutrageous 47g",
    nameEn: "Reese's Nutrageous 47g",
    priceCents: 150,
    categorySlug: "cioccolato",
    brandSlug: "reeses",
    attributes: { peso: "47g" },
  },
  {
    slug: "reeses-sticks-85g",
    nameIt: "Reese's Sticks 85g",
    nameEn: "Reese's Sticks 85g",
    priceCents: 250,
    categorySlug: "cioccolato",
    brandSlug: "reeses",
    attributes: { peso: "85g" },
  },
  {
    slug: "kinder-happy-hippo-nocciola-5pz",
    nameIt: "Kinder Happy Hippo Nocciola 5pz",
    nameEn: "Kinder Happy Hippo Hazelnut 5pcs",
    descIt: "Wafer croccanti a forma di ippopotamo con crema alla nocciola.",
    descEn: "Crunchy hippo-shaped wafers with hazelnut cream.",
    priceCents: 199,
    compareAtCents: 300,
    categorySlug: "cioccolato",
    brandSlug: "kinder",
    attributes: { peso: "5 pz" },
    isFeatured: true,
  },
  {
    slug: "hersheys-cookies-cream-43g",
    nameIt: "Hershey's Cookies 'n' Creme 43g",
    nameEn: "Hershey's Cookies 'n' Creme 43g",
    priceCents: 200,
    categorySlug: "cioccolato",
    brandSlug: "hersheys",
    attributes: { peso: "43g" },
  },
  {
    slug: "hersheys-milk-chocolate-43g",
    nameIt: "Hershey's Milk Chocolate 43g",
    nameEn: "Hershey's Milk Chocolate 43g",
    priceCents: 200,
    categorySlug: "cioccolato",
    brandSlug: "hersheys",
    attributes: { peso: "43g" },
  },
  {
    slug: "reeses-pieces-43g",
    nameIt: "Reese's Pieces 43g",
    nameEn: "Reese's Pieces 43g",
    priceCents: 250,
    categorySlug: "cioccolato",
    brandSlug: "reeses",
    attributes: { peso: "43g" },
  },

  // ───────── CARAMELLE ─────────
  {
    slug: "haribo-goldbears-100g",
    nameIt: "Haribo Goldbears 100g",
    nameEn: "Haribo Goldbears 100g",
    descIt: "Gli orsetti gommosi originali Haribo, gusti assortiti alla frutta.",
    descEn: "The original Haribo gummy bears, assorted fruit flavors.",
    priceCents: 199,
    categorySlug: "caramelle",
    brandSlug: "haribo",
    attributes: { peso: "100g", tipologia: "Gelatine" },
    isFeatured: true,
  },
  {
    slug: "trolli-sour-brite-crawlers-142g",
    nameIt: "Trolli Sour Brite Crawlers 142g",
    nameEn: "Trolli Sour Brite Crawlers 142g",
    priceCents: 399,
    categorySlug: "caramelle",
    brandSlug: "trolli",
    attributes: { peso: "142g", tipologia: "Gelatine acide" },
    isNew: true,
  },
  {
    slug: "warheads-extreme-sour-49g",
    nameIt: "Warheads Extreme Sour 49g",
    nameEn: "Warheads Extreme Sour 49g",
    descIt: "Le caramelle più acide del mondo. Cinque gusti assortiti.",
    descEn: "The sourest candy in the world. Five assorted flavors.",
    priceCents: 299,
    categorySlug: "caramelle",
    brandSlug: "warheads",
    attributes: { peso: "49g", tipologia: "Acide" },
  },
  {
    slug: "sour-patch-kids-141g",
    nameIt: "Sour Patch Kids 141g",
    nameEn: "Sour Patch Kids 141g",
    priceCents: 399,
    categorySlug: "caramelle",
    brandSlug: "sour-patch",
    attributes: { peso: "141g", tipologia: "Gelatine acide" },
    isFeatured: true,
  },
  {
    slug: "nerds-rainbow-141g",
    nameIt: "Nerds Rainbow 141g",
    nameEn: "Nerds Rainbow 141g",
    priceCents: 499,
    categorySlug: "caramelle",
    brandSlug: "nerds",
    attributes: { peso: "141g" },
    isNew: true,
  },
  {
    slug: "nerds-gummy-clusters-142g",
    nameIt: "Nerds Gummy Clusters 142g",
    nameEn: "Nerds Gummy Clusters 142g",
    priceCents: 599,
    categorySlug: "caramelle",
    brandSlug: "nerds",
    attributes: { peso: "142g" },
    isFeatured: true,
    isNew: true,
  },
  {
    slug: "skittles-original-61g",
    nameIt: "Skittles Original 61g",
    nameEn: "Skittles Original 61g",
    descIt: "Taste the rainbow. Caramelle masticabili ai 5 gusti di frutta.",
    descEn: "Taste the rainbow. Chewy fruit-flavored candies.",
    priceCents: 199,
    categorySlug: "caramelle",
    brandSlug: "skittles",
    attributes: { peso: "61g" },
  },
  {
    slug: "mike-and-ike-141g",
    nameIt: "Mike and Ike Original Fruits 141g",
    nameEn: "Mike and Ike Original Fruits 141g",
    priceCents: 349,
    categorySlug: "caramelle",
    brandSlug: "mike-ike",
    attributes: { peso: "141g" },
  },
  {
    slug: "trolli-planet-gummi-150g",
    nameIt: "Trolli Planet Gummi 150g",
    nameEn: "Trolli Planet Gummi 150g",
    priceCents: 399,
    categorySlug: "caramelle",
    brandSlug: "trolli",
    attributes: { peso: "150g" },
    isNew: true,
  },

  // ───────── PATATINE & POPCORN ─────────
  {
    slug: "pringles-original-175g",
    nameIt: "Pringles Original 175g",
    nameEn: "Pringles Original 175g",
    descIt: "Le classiche patatine Pringles dal gusto originale, croccanti e saporite.",
    descEn: "The classic original Pringles, crispy and tasty.",
    priceCents: 250,
    categorySlug: "patatine-popcorn",
    brandSlug: "pringles",
    attributes: { peso: "175g", gusto: "Original" },
    isFeatured: true,
  },
  {
    slug: "pringles-cheese-chilli-160g",
    nameIt: "Pringles Cheese & Chilli 160g",
    nameEn: "Pringles Cheese & Chilli 160g",
    priceCents: 250,
    categorySlug: "patatine-popcorn",
    brandSlug: "pringles",
    attributes: { peso: "160g", gusto: "Cheese & Chilli" },
  },
  {
    slug: "pringles-paprika-165g",
    nameIt: "Pringles Paprika 165g",
    nameEn: "Pringles Paprika 165g",
    priceCents: 250,
    categorySlug: "patatine-popcorn",
    brandSlug: "pringles",
    attributes: { peso: "165g", gusto: "Paprika" },
  },
  {
    slug: "pringles-salt-vinegar-165g",
    nameIt: "Pringles Salt & Vinegar 165g",
    nameEn: "Pringles Salt & Vinegar 165g",
    priceCents: 250,
    categorySlug: "patatine-popcorn",
    brandSlug: "pringles",
    attributes: { peso: "165g", gusto: "Salt & Vinegar" },
  },
  {
    slug: "pringles-flame-spicy-chilli-lime-160g",
    nameIt: "Pringles Flame Spicy Chilli & Lime 160g",
    nameEn: "Pringles Flame Spicy Chilli & Lime 160g",
    priceCents: 350,
    categorySlug: "patatine-popcorn",
    brandSlug: "pringles",
    attributes: { peso: "160g", gusto: "Chilli & Lime" },
    isNew: true,
  },
  {
    slug: "chazz-naughty-cheddar-90g",
    nameIt: "Chazz Potato Chips Naughty Cheddar 90g",
    nameEn: "Chazz Potato Chips Naughty Cheddar 90g",
    priceCents: 300,
    categorySlug: "patatine-popcorn",
    brandSlug: "chazz",
    attributes: { peso: "90g", gusto: "Cheddar" },
  },
  {
    slug: "chazz-caramelised-onion-130g",
    nameIt: "Chazz Caramelised Onion 130g",
    nameEn: "Chazz Caramelised Onion 130g",
    priceCents: 350,
    categorySlug: "patatine-popcorn",
    brandSlug: "chazz",
    attributes: { peso: "130g", gusto: "Cipolla caramellata" },
  },
  {
    slug: "chazz-jalapeno-habanero-90g",
    nameIt: "Chazz Jalapeño & Habanero 90g",
    nameEn: "Chazz Jalapeño & Habanero 90g",
    priceCents: 350,
    categorySlug: "patatine-popcorn",
    brandSlug: "chazz",
    attributes: { peso: "90g", gusto: "Jalapeño Habanero", spice: "Piccante" },
    isNew: true,
  },
  {
    slug: "jimmys-popcorn-sweet-150g",
    nameIt: "Jimmy's Popcorn Sweet Family Bag 150g",
    nameEn: "Jimmy's Popcorn Sweet Family Bag 150g",
    priceCents: 200,
    categorySlug: "patatine-popcorn",
    brandSlug: "jimmys",
    attributes: { peso: "150g", gusto: "Dolce" },
  },
  {
    slug: "jimmys-popcorn-salt-100g",
    nameIt: "Jimmy's Popcorn Salt 100g",
    nameEn: "Jimmy's Popcorn Salt 100g",
    priceCents: 250,
    categorySlug: "patatine-popcorn",
    brandSlug: "jimmys",
    attributes: { peso: "100g", gusto: "Salato" },
  },
  {
    slug: "totas-pollo-asado-130g",
    nameIt: "Totas Patatas Fritas Pollo Asado 130g",
    nameEn: "Totas Roast Chicken Crisps 130g",
    priceCents: 150,
    categorySlug: "patatine-popcorn",
    brandSlug: "totas",
    attributes: { peso: "130g", gusto: "Pollo arrosto" },
  },
  {
    slug: "totas-queso-cebolla-130g",
    nameIt: "Totas Queso y Cebolla 130g",
    nameEn: "Totas Cheese & Onion 130g",
    priceCents: 150,
    categorySlug: "patatine-popcorn",
    brandSlug: "totas",
    attributes: { peso: "130g", gusto: "Formaggio e Cipolla" },
  },

  // ───────── BEVANDE AMERICANE ─────────
  {
    slug: "coca-cola-cherry-330ml",
    nameIt: "Coca-Cola Cherry 330ml",
    nameEn: "Coca-Cola Cherry 330ml",
    descIt: "La classica Coca-Cola con un twist di ciliegia.",
    descEn: "Classic Coca-Cola with a cherry twist.",
    priceCents: 150,
    categorySlug: "bevande-americane",
    brandSlug: "coca-cola",
    attributes: { peso: "330ml", gusto: "Ciliegia" },
    isFeatured: true,
  },
  {
    slug: "coca-cola-vanilla-330ml",
    nameIt: "Coca-Cola Vanilla 330ml",
    nameEn: "Coca-Cola Vanilla 330ml",
    priceCents: 200,
    categorySlug: "bevande-americane",
    brandSlug: "coca-cola",
    attributes: { peso: "330ml", gusto: "Vaniglia" },
  },
  {
    slug: "dr-pepper-cherry-355ml",
    nameIt: "Dr Pepper Cherry 355ml",
    nameEn: "Dr Pepper Cherry 355ml",
    priceCents: 200,
    categorySlug: "bevande-americane",
    brandSlug: "dr-pepper",
    attributes: { peso: "355ml", gusto: "Ciliegia" },
    isFeatured: true,
  },
  {
    slug: "fanta-grape-355ml",
    nameIt: "Fanta Grape 355ml",
    nameEn: "Fanta Grape 355ml",
    priceCents: 180,
    categorySlug: "bevande-americane",
    brandSlug: "fanta",
    attributes: { peso: "355ml", gusto: "Uva" },
  },
  {
    slug: "mountain-dew-baja-blast-355ml",
    nameIt: "Mountain Dew Baja Blast 355ml",
    nameEn: "Mountain Dew Baja Blast 355ml",
    descIt: "L'iconica Mountain Dew Baja Blast con gusto tropicale lime.",
    descEn: "The iconic Mountain Dew Baja Blast with tropical lime flavor.",
    priceCents: 290,
    categorySlug: "bevande-americane",
    brandSlug: "mountain-dew",
    attributes: { peso: "355ml", gusto: "Baja Blast" },
    isFeatured: true,
    isNew: true,
  },
  {
    slug: "calypso-original-lemonade-473ml",
    nameIt: "Calypso Original Lemonade 473ml",
    nameEn: "Calypso Original Lemonade 473ml",
    priceCents: 399,
    categorySlug: "bevande-americane",
    brandSlug: "calypso",
    attributes: { peso: "473ml", gusto: "Limonata classica" },
  },
  {
    slug: "calypso-ocean-blue-lemonade-473ml",
    nameIt: "Calypso Ocean Blue Lemonade 473ml",
    nameEn: "Calypso Ocean Blue Lemonade 473ml",
    priceCents: 399,
    categorySlug: "bevande-americane",
    brandSlug: "calypso",
    attributes: { peso: "473ml", gusto: "Ocean Blue" },
  },
  {
    slug: "calypso-strawberry-lemonade-473ml",
    nameIt: "Calypso Strawberry Lemonade 473ml",
    nameEn: "Calypso Strawberry Lemonade 473ml",
    priceCents: 399,
    categorySlug: "bevande-americane",
    brandSlug: "calypso",
    attributes: { peso: "473ml", gusto: "Fragola" },
  },
  {
    slug: "calypso-triple-melon-473ml",
    nameIt: "Calypso Triple Melon Lemonade 473ml",
    nameEn: "Calypso Triple Melon Lemonade 473ml",
    priceCents: 399,
    categorySlug: "bevande-americane",
    brandSlug: "calypso",
    attributes: { peso: "473ml", gusto: "Triple Melon" },
    isNew: true,
  },
  {
    slug: "prime-blue-raspberry",
    nameIt: "Prime Blue Raspberry",
    nameEn: "Prime Blue Raspberry",
    descIt: "Idratante Prime al gusto blue raspberry — la bevanda più virale del momento.",
    descEn: "Prime Hydration in blue raspberry — the most viral drink right now.",
    priceCents: 490,
    categorySlug: "bevande-americane",
    brandSlug: "prime",
    attributes: { peso: "500ml", gusto: "Blue Raspberry" },
    isFeatured: true,
  },
  {
    slug: "prime-tropical-punch",
    nameIt: "Prime Tropical Punch",
    nameEn: "Prime Tropical Punch",
    priceCents: 490,
    categorySlug: "bevande-americane",
    brandSlug: "prime",
    attributes: { peso: "500ml", gusto: "Tropical Punch" },
  },
  {
    slug: "prime-meta-moon",
    nameIt: "Prime Meta Moon",
    nameEn: "Prime Meta Moon",
    priceCents: 490,
    categorySlug: "bevande-americane",
    brandSlug: "prime",
    attributes: { peso: "500ml", gusto: "Meta Moon" },
    isNew: true,
  },
  {
    slug: "arizona-hero-hydration-peach-mango-473ml",
    nameIt: "Arizona Hero Hydration Peach Mango 473ml",
    nameEn: "Arizona Hero Hydration Peach Mango 473ml",
    priceCents: 590,
    categorySlug: "bevande-americane",
    brandSlug: "arizona",
    attributes: { peso: "473ml", gusto: "Peach Mango" },
    isNew: true,
  },
  {
    slug: "arizona-hero-hydration-blueberry-473ml",
    nameIt: "Arizona Hero Hydration Blueberry 473ml",
    nameEn: "Arizona Hero Hydration Blueberry 473ml",
    priceCents: 590,
    categorySlug: "bevande-americane",
    brandSlug: "arizona",
    attributes: { peso: "473ml", gusto: "Blueberry" },
  },
  {
    slug: "monster-energy-original-500ml",
    nameIt: "Monster Energy Original 500ml",
    nameEn: "Monster Energy Original 500ml",
    priceCents: 250,
    compareAtCents: 300,
    categorySlug: "bevande-americane",
    brandSlug: "monster",
    attributes: { peso: "500ml", gusto: "Original" },
  },

  // ───────── SNACK DOLCI ─────────
  {
    slug: "oreo-cookies-154g",
    nameIt: "Oreo Cookies Original 154g",
    nameEn: "Oreo Cookies Original 154g",
    descIt: "I biscotti al cacao con crema bianca più famosi al mondo.",
    descEn: "The world's most famous cocoa cookies with cream filling.",
    priceCents: 249,
    categorySlug: "snack-dolci",
    brandSlug: "oreo",
    attributes: { peso: "154g" },
    isFeatured: true,
  },
  {
    slug: "oreo-double-stuf-157g",
    nameIt: "Oreo Double Stuf 157g",
    nameEn: "Oreo Double Stuf 157g",
    priceCents: 350,
    categorySlug: "snack-dolci",
    brandSlug: "oreo",
    attributes: { peso: "157g", gusto: "Double cream" },
  },
  {
    slug: "oreo-golden-154g",
    nameIt: "Oreo Golden 154g",
    nameEn: "Oreo Golden 154g",
    priceCents: 349,
    categorySlug: "snack-dolci",
    brandSlug: "oreo",
    attributes: { peso: "154g", gusto: "Vaniglia" },
    isNew: true,
  },
  {
    slug: "hersheys-syrup-chocolate-680g",
    nameIt: "Hershey's Syrup Chocolate 680g",
    nameEn: "Hershey's Syrup Chocolate 680g",
    descIt: "Sciroppo al cioccolato Hershey's per topping, pancake e milkshake.",
    descEn: "Hershey's chocolate syrup for toppings, pancakes and milkshakes.",
    priceCents: 690,
    categorySlug: "snack-dolci",
    brandSlug: "hersheys",
    attributes: { peso: "680g" },
  },

  // ───────── CEREALI ─────────
  {
    slug: "lucky-charms-422g",
    nameIt: "Lucky Charms 422g",
    nameEn: "Lucky Charms 422g",
    descIt: "Cereali a forma di trifoglio e marshmallow colorati. Iconici dal 1964.",
    descEn: "Cereal with marshmallow shapes. Iconic since 1964.",
    priceCents: 890,
    categorySlug: "cereali",
    brandSlug: "lucky-charms",
    attributes: { peso: "422g" },
    isFeatured: true,
  },
  {
    slug: "froot-loops-286g",
    nameIt: "Froot Loops 286g",
    nameEn: "Froot Loops 286g",
    priceCents: 750,
    categorySlug: "cereali",
    brandSlug: "froot-loops",
    attributes: { peso: "286g" },
    isFeatured: true,
  },
  {
    slug: "lucky-charms-magical-clovers-323g",
    nameIt: "Lucky Charms Magical Clovers 323g",
    nameEn: "Lucky Charms Magical Clovers 323g",
    priceCents: 790,
    categorySlug: "cereali",
    brandSlug: "lucky-charms",
    attributes: { peso: "323g" },
    isNew: true,
  },
];

// Genera URL placehold.co per immagine PNG di un prodotto.
// L'utente sostituirà queste immagini dal pannello admin con upload Cloudinary.
export function placeholderImage(product: SeedProduct, category: SeedCategory, brand: SeedBrand): string {
  const bg = product.imageColor ?? category.color;
  const label = encodeURIComponent(`${brand.name}\n${product.nameIt.slice(0, 40)}`);
  return `https://placehold.co/600x600/${bg}/FFFFFF.png?text=${label}&font=montserrat`;
}
